export const RULES_GOAL = 0.4
export const RULES_ASSIST = 0.3
export const RULES_CLEANSHEET = 0.1
export const RULES_CLEANSHEET_GK = 0.2
export const RULES_SAVE = 0.3
export const RULES_GOAL_FINAL = 0.6
export const RULES_ASSIST_FINAL = 0.5
export const RULES_CLEANSHEET_FINAL = 0.2
export const RULES_CLEANSHEET_GK_FINAL = 0.4
export const RULES_SAVE_FINAL = 0.5
export const RULES_FIXTURE_WIN = 4
export const RULES_FIXTURE_WIN_CAPTAIN = 5
export const RULES_FIXTURE_WIN_FINAL = 10 
export const RULES_FIXTURE_WIN_FINAL_CAPTAIN = 10 
export const RULES_FIXTURE_TIE = 2
export const RULES_FIXTURE_TIE_CAPTAIN = 2.5
export const RULES_FIXTURE_TIE_FINAL = 5 
export const RULES_FIXTURE_TIE_FINAL_CAPTAIN = 5 
export const RULES_MATCH_WIN = 0.1
export const RULES_MATCH_WIN_CAPTAIN = RULES_MATCH_WIN
export const RULES_MATCH_WIN_FINAL = 0.2 
export const RULES_MATCH_WIN_FINAL_CAPTAIN = RULES_MATCH_TIE_FINAL 
export const RULES_MATCH_WIN_PENALTIES = RULES_MATCH_TIE
export const RULES_MATCH_WIN_PENALTIES_CAPTAIN = RULES_MATCH_WIN_PENALTIES
export const RULES_MATCH_WIN_PENALTIES_FINAL = RULES_MATCH_WIN_FINAL
export const RULES_MATCH_WIN_PENALTIES_FINAL_CAPTAIN = RULES_MATCH_WIN_PENALTIES_FINAL
export const RULES_MATCH_LOSE_PENALTIES = RULES_MATCH_WIN_PENALTIES
export const RULES_MATCH_LOSE_PENALTIES_CAPTAIN = RULES_MATCH_WIN_PENALTIES_CAPTAIN
export const RULES_MATCH_LOSE_PENALTIES_FINAL = RULES_MATCH_WIN_PENALTIES_FINAL
export const RULES_MATCH_LOSE_PENALTIES_FINAL_CAPTAIN = RULES_MATCH_WIN_PENALTIES_FINAL
export const RULES_MATCH_TIE = 0.1
export const RULES_MATCH_TIE_CAPTAIN = RULES_MATCH_TIE
export const RULES_MATCH_TIE_FINAL = 0.2
export const RULES_MATCH_TIE_FINAL_CAPTAIN = RULES_MATCH_TIE_FINAL
export const RULES_MVP = 1.5
export const RULES_MVP_FINAL = 5
export const RULES_FAIRPLAY = 1
export const RULES_PUNISH = -1
export const RULES_YELLOW = -0.1
export const RULES_SECOND_YELLOW = -0.2
export const RULES_RED = 0.3




export const calculatePoints = (players, fixtures, playerId, fixtureId) => {
    return 0
}